# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available optio

before_script:
  - mkdir ~/bin
  - PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
  - mkdir android
  - cd android
  - git config --global user.name "Jony"
  - git config --global user.email "jonyg1355@gmail.com"
  - repo init -u https://android.googlesource.com/platform/manifest --quiet
  - repo sync -f --quiet 
 
upload: 
  stage: build
  script:
    - git remote add origin https://gitlab.com/lakshit1/android.git
    - git push -u origin --all
    - git push -u origin --tags
  

